import { DefaultTheme } from "styled-components";

export const calcRem = (size: number) => `${size / 16}rem`;

export const theme: DefaultTheme = {
  boxShadow: {
    skyblue:
      "0 0 0 1px rgba(18, 100, 163, 1), 0 0 0 5px rgba(29, 155, 209, 0.3)",
    darkgray:
      "0 0 4px 3px rgba(0, 0, 0, 0.05), 0 0 4px 10px rgba(0, 0, 0, 0.03)",
    black: "0 0 8px 8px rgba(0, 0, 0, 0.3), 0 0 8px 8px rgba(0, 0, 0, 0.3)",
    bottomRed: "0 4px 2px -2px rgb(240, 115, 98)",
    bottomSkyBlue: "0 4px 2px -2px rgb(0, 115, 198)",
    thickDarkGray: "0 10px 5px 5px rgba(0, 0, 0, 0.05)",
  },
  color: {
    main: "#4a154b",
    lightBlack: "#1d1c1d",
    black1: "#111",
    black2: "#222",
    black3: "#333",
    black4: "#444",
    black5: "#555",
    black6: "#666",
    black7: "#777",
    black8: "#888",
    black9: "#999",

    gray1: "#4A5566",
    gray2: "#888",
    gray3: "#bbb",

    darkgray: "#555",

    lightGray1: "#d0d0d0",
    lightGray2: "#e0e0e0",
    lightGray3: "#f0f0f0",

    purple1: "#350d36",
    purple2: "#3f0e40",
    purple3: "#431e44",

    green1: "#007a5a",
    green2: "#008a6a",
    green3: "#25D179",

    white: "#fff",

    red1: "#f07362",

    blue1: "#3E495C",
    blue2: "#0C387B",
    blue3: "#0D47A1",
    blue4: "#1565C0",
    blue5: "#97B5DD",
    blue6: "#BBDEFB",
    blue7: "#f5faff",

    modalWhite: "#f9f9f9",
    semiWhite: "#fafbfc",

    yellow: "#e8912d",
    warningRed: "#D73A49",
    onConnect: "#2bac76",

    channelItemColor: "#bcabbc",
    channelBorder: "rgb(82,38,83)",
    threadHover: "#faf9f9",
    googleColor: "#4285f4",

    darkBlue1: "#2D353C",
    darkBlue2: "#4F5B69",
    lightBlue: "#BEDFEC",
    coralBlue: "#70B2E6",

    jade: "#36ACAC",
  },
  size: {
    font: {
      xxxxxs: calcRem(4),
      xxxxs: calcRem(6),
      xxxs: calcRem(8),
      xxs: calcRem(10),
      xs: calcRem(12),
      s: calcRem(14),
      m: calcRem(16),
      l: calcRem(18),
      xl: calcRem(20),
      xxl: calcRem(22),
      xxxl: calcRem(24),
      bigContentLarge: calcRem(40),
      bigContentMedium: calcRem(30),
      bigContentSmall: calcRem(25),
      mediumContentLarge: calcRem(19),
      mediumContentMedium: calcRem(16),
      mediumContentSmall: calcRem(13),
      cardContent: calcRem(20),
      veryBigContentLarge: calcRem(50),
      veryBigContentMedium: calcRem(40),
      veryBigContentSmall: calcRem(35),
      influenceContent: calcRem(20),
      smallContentLarge: calcRem(15),
      smallContentMedium: calcRem(13),
      smallContentSmall: calcRem(11),
    },
    padding: {
      fourSide: {
        productApplicationRemoveButton: calcRem(5),
        gridCardItem: calcRem(20),
      },
      vertical: {
        container: "15%",
        productApplicationBottomContainer: calcRem(10),
        productApplicationButtonBox: calcRem(5),
        productApplicationLargeChoiceButton: calcRem(10),
        productApplicationMediumChoiceButton: calcRem(5),
        productApplicationSmallChoiceButton: calcRem(2),
      },
      horizontal: {
        header: {
          large: calcRem(20),
          small: calcRem(15),
        },
        leftHeaderMenu: calcRem(15),
        carouselLarge: calcRem(16),
        carouselMedium: calcRem(13),
        carouselSmall: calcRem(10),
        productApplicationBottomContainer: calcRem(10),
        productApplicationButtonBox: calcRem(16),
        productApplicationLargeChoiceButton: calcRem(20),
        productApplicationMediumChoiceButton: calcRem(10),
        productApplicationSmallChoiceButton: calcRem(5),
        reviews: "15%",
      },
    },
    width: {
      headerLargeStyledA: calcRem(150),
      headerSmallStyledA: calcRem(100),
      contentLargeStyledA: calcRem(350),
      contentSmallStyledA: calcRem(300),
      headerLargeLogo: calcRem(150),
      headerSmallLogo: calcRem(30),
      leftHeaderMenuItem: calcRem(150),
      leftHeaderButtonLarge: calcRem(300),
      leftHeaderButtonSmall: calcRem(250),
      carouselLargeContainer: calcRem(270),
      carouselMediumContainer: calcRem(189),
      carouselSmallContainer: calcRem(160),
      carouselLargeButton: calcRem(30),
      carouselMediumButton: calcRem(21),
      carouselSmallButton: calcRem(15),
      tshirtLargeImg: calcRem(20),
      tshirtMediumImg: calcRem(15),
      tshirtSmallImg: calcRem(10),
      binLargeImg: calcRem(15),
      binMediumImg: calcRem(10),
      binSmallImg: calcRem(5),
      hamburgerLarge: calcRem(25),
      hamburgerMedium: calcRem(21),
      hamburgerSmall: calcRem(12),
      carouselLargeContainerThreeTimes: calcRem(270 * 3),
      carouselMediumContainerThreeTimes: calcRem(189 * 3),
      carouselSmallContainerThreeTimes: calcRem(135 * 3),
      gridCardImg: calcRem(100),
      gridLargeBrand: calcRem(200),
      gridMediumBrand: calcRem(150),
      gridSmallBrand: calcRem(100),
      youtubeLarge: calcRem(230),
      youtubeSmall: calcRem(170),
      brandImg: calcRem(150),
    },
    height: {
      headerLargeStyledA: calcRem(50),
      headerSmallStyledA: calcRem(40),
      contentLargeStyledA: calcRem(70),
      contentSmallStyledA: calcRem(60),
      headerLargeDiv: calcRem(75),
      headerSmallDiv: calcRem(60),
      leftHeaderMenuItem: calcRem(50),
      carouselLargeContainer: calcRem(585),
      carouselMediumContainer: calcRem(409.5),
      carouselSmallContainer: calcRem(292.5),
      carouselLargeButton: calcRem(30),
      carouselMediumButton: calcRem(21),
      carouselSmallButton: calcRem(15),
      tshirtLargeImg: calcRem(20),
      tshirtMediumImg: calcRem(15),
      tshirtSmallImg: calcRem(10),
      binLargeImg: calcRem(18),
      binMediumImg: calcRem(13),
      binSmallImg: calcRem(8),
      hamburgerLarge: calcRem(25),
      hamburgerMedium: calcRem(21),
      hamburgerSmall: calcRem(15),
      gridCardItem: calcRem(350),
      gridCardImg: calcRem(100),
      gridReviewItem: calcRem(370),
    },
    margin: {
      horizontal: {
        carouselButton: calcRem(16),
        productApplicationRemoveButtonIcon: calcRem(3),
      },
    },
    border: {
      radius: calcRem(5),
    },
    shadow: {
      blur: calcRem(3),
      spread: calcRem(1),
    },
  },
  fontWeight: {
    bold: 600,
  },
};
